GarageStoreWeb/Areas/Admin/Controllers/CategoryController.cs
using GarageStore.DataAccess.Repository.IRepository;
using GarageStore.Models;
using GarageStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GarageStoreWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public CategoryController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _unitOfWork.Category.GetAll();
            return View(categories);
        }

        //GET
        public IActionResult Upsert(int? id)
        {
            Category category = new();
            if (id == null || id == 0)
            {
                return View(category);
            }
            else
            {
                category = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
                return View(category);
            }
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category obj, IFormFile? file, IFormFileCollection? files)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\categories");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\categories\" + fileName + extension;
                }
                if (obj.Id == 0)
                {
                    _unitOfWork.Category.Add(obj);
                    TempData["success"] = "Kategória létrehozása sikeres!";
                }
                else
                {
                    _unitOfWork.Category.Update(obj);
                    TempData["success"] = "Kategória frissítése sikeres!";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var categoryList = _unitOfWork.Category.GetAll().OrderBy(u => u.DisplayOrder);
            return Json(new { data = categoryList });
        }

        //POST
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Hiba törlés közben!" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Kategória törlése sikeres!" });

        }
        #endregion
    }
}

GarageStoreWeb/Areas/Admin/Controllers/OrderController.cs
using GarageStore.DataAccess.Repository.IRepository;
using GarageStore.Models;
using GarageStore.Models.ViewModels;
using GarageStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GarageStoreWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		[BindProperty]
		public OrderVM OrderVM { get; set; }
		public OrderController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Details(int orderId)
		{
			OrderVM = new OrderVM()
			{
				OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => u.Id == orderId,
				includeProperties: "ApplicationUser,DeliveryOption"),
				OrderDetails = _unitOfWork.OrderDetail.GetAll(u => u.OrderId == orderId,
				includeProperties: "Product")
			};
			return View(OrderVM);
		}
		#region API CALLS
		[HttpGet]
		public IActionResult GetAll(string status)
		{
			IEnumerable<OrderHeader> orderHeaders;

			if (User.IsInRole(SD.Role_Admin))
			{
				orderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser");
			}
			else
			{
				var claimsIdentity = (ClaimsIdentity)User.Identity;
				var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
				orderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == claims.Value,
					includeProperties: "ApplicationUser");
			}

			switch(status)
			{
				case "pending":
					orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.Payment_Status_Pending);
					break;
				case "approved":
					orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.Status_Approved);
					break;
				case "shipped":
					orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.Status_Shipped);
					break;
				default:
					break;
			}
			orderHeaders = orderHeaders.OrderByDescending(u => u.Id);
			return Json(new { data = orderHeaders });
		}
		#endregion
	}
}

GarageStoreWeb/ViewComponents/ShoppingCartViewComponent.cs
using GarageStore.DataAccess.Repository.IRepository;
using GarageStore.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace GarageStoreWeb.ViewComponents
{
	public class ShoppingCartViewComponent : ViewComponent
	{
		private readonly IUnitOfWork _unitOfWork;
		public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
				{
					return View(HttpContext.Session.GetInt32(SD.SessionCart));
				}
				else
				{
					HttpContext.Session.SetInt32(SD.SessionCart,
						_unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
					return View(HttpContext.Session.GetInt32(SD.SessionCart));
				}
			}
			else
			{
				HttpContext.Session.Clear();
				return View(0);
			}
		}
	}
}

GarageStoreWeb/Views/Shared/_Layout.cshtml
@using GarageStore.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Garage Store</title>
    <link rel="stylesheet" href="~/css/bootSwatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />
    <link rel="icon" type="image/png" href="~/images/logo.png" />
</head>
<body>
    <div class="container pb-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
    <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"><img src="\images\logo.png" alt="" width="30" height="30" class="d-inline-block align-text-middle">Garage Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Főoldal</a>
        </li>
        @if (User.IsInRole(SD.Role_Admin))
        {
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Tartalom kezelés</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Kategória</a>
                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Termék</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Új felhasználó</a>
                </div>
            </li>
        }
        <li class="nav-item">
          <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Rendelés kezelés</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                    @await Component.InvokeAsync("ShoppingCart")
            </a>
        </li>
      </ul>
        <form method="get" asp-area="Customer" asp-controller="Home"  asp-action="Index" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input id="searchText" type="text" class="form-control" placeholder="Keresés" value="@ViewData["GetSearchDetails"]" name="searchValue" onkeyup="checkSearchInput()">
                <span class="input-group-btn">
                    <button type="submit" id="searchButton" class="btn btn-default" disabled>
                    <i class="bi bi-search"></i>
                    </button>
                </span>
            </div>
        </form>
      <partial name="_LoginPartial" />
    </div>
  </div>
</nav>
</div>
    <div class="container pt-5">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification" />
        </main>
    </div>

    <footer class="footer bg-primary text-center">
        <p class="lead text-white">Garage Store</p>
        <a href="#" class="position-absolute bottom-0 end-0 p-1">
            <i class="bi bi-arrow-up-circle h2 text-white"></i>
        </a>
    <footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        function checkSearchInput(){
            var text = document.getElementById("searchText").value.trim();
            var cansubmit = (text.length < 2);
            document.getElementById("searchButton").disabled = cansubmit;
        };
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GarageStoreWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}